spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox?schema=sandbox
    username: user
    password: user123
logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
